# Generated by Django 5.0.4 on 2024-04-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_code", models.CharField(max_length=6, unique=True)),
                ("foreign_code", models.CharField(blank=True, max_length=6, null=True)),
                ("is_owners_code_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="invite_code",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to="users.invitecode",
            ),
        ),
    ]
